language: node_js
node_js:
  - "10"
addons:
  apt:
    update: true
    packages:
    - genisoimage

install:
  - cd src
  - npm install
  - cd ..

jobs:
  include:
    - stage: release
      script: 
        - rm -rf ./SD_CARD
        - node ./src/index_fr.js
        - genisoimage -o sd_image.iso SD_CARD
        - zip -r sd_image.iso.zip sd_image.iso
        - zip -r all_files.zip SD_CARD

branches:
  only:
    - master
    - stable

before_deploy:
  - export GATSO_UPDATE_MAX=`date -d @$(cat ./SD_CARD/manifest.txt | sort -n | tail -1) +%Y-%m-%d`
  - "[[ $TRAVIS_TAG ]] || export TRAVIS_TAG=\"${TAG_PREFIX}${TRAVIS_BRANCH}.${GATSO_UPDATE_MAX}\""
  - git config --local user.name "$USER_NAME"
  - git config --local user.email "$USER_EMAIL"
  - git tag --force "$TRAVIS_TAG" $TRAVIS_COMMIT

deploy:
  - provider: releases
    name: $TRAVIS_TAG
    overwrite: true
    tags: false
    prerelease: true
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file:
      - "all_files.zip"
      - "sd_image.iso.zip"
    on:
      tags: false
      branch: 
        - master
  - provider: releases
    name: $TRAVIS_TAG
    overwrite: true
    prerelease: false
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file:
      - "all_files.zip"
      - "sd_image.iso.zip"
    on:
      tags: true
