language: node_js
node_js:
  - "10"
addons:
  apt:
    update: true
    packages:
    - genisoimage

cache:
  directories:
    - ./CACHE
    
branches:
  only:
    - master
    #- stable
    #- develop
    - travisci


before_install:
  - printenv
  - ls -al
  - cd src
  - npm install
  - cd ..
  - pip install --user configparser pandas pillow
  - ls -al

install:
  - ls -al
  ############################################
  - find ./CACHE -type f -mmin +360 -delete
  ############################################
  - ls -al

before_script:
  - ls -al
  ############################################
  - ./make.sh --install --cache
  ############################################
  - ls -al

script: 
  - ls -al
  ############################################
  - CNX='CNX_GATSO_FR'
  - ./make.sh -arg=hasCache --run -arg="$CNX" -arg=csv
  - cp ./RELEASES ./RELEASES_GATSO_FR
  ############################################
  - CNX='CNX_GATSO_FR CNX_GATSO_EU'
  - ./make.sh -arg=hasCache --run -arg="$CNX" -arg=csv
  - cp ./RELEASES ./RELEASES_GATSO_EU
  ############################################
  - CNX='CNX_FUEL_FR'
  - ./make.sh -arg=hasCache --run -arg="$CNX" -arg=csv
  - cp ./RELEASES ./RELEASES_FUEL_FR
  ############################################
  - CNX='CNX_GATSO_FR CNX_FUEL_FR'
  - ./make.sh -arg=hasCache --run -arg="$CNX" -arg=csv
  - cp ./RELEASES ./RELEASES_ALL_FR
  ############################################
  - ./make.sh -arg=hasCache --run --image
  - cp ./RELEASES
  ############################################
  - ls -al

before_deploy:
  - ls -al
  ############################################
  - export GATSO_UPDATE_MAX=`date -d @$(cat ./BUILD/version.txt | sort -n | tail -1) +%Y-%m-%d`
  - export RELEASE_DESCRIPTION=`cat ./BUILD/manifest.txt`
  ############################################
  - echo "TRAVIS_TAG=$TRAVIS_TAG;"
  #- echo "TAG_PREFIX=$TAG_PREFIX;"
  #- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH;"
  #- echo "GATSO_UPDATE_MAX=$GATSO_UPDATE_MAX;"
  #- "[[ $TRAVIS_TAG ]] || export TRAVIS_TAG=\"${TAG_PREFIX}${TRAVIS_BRANCH}.${GATSO_UPDATE_MAX}\""
  ############################################
  - ./make.sh --uninstall
  ############################################
  - ls -al
  ############################################
  - git config --local user.name "$USER_NAME"
  - git config --local user.email "$USER_EMAIL"
  #- git tag --force "$TRAVIS_TAG" $TRAVIS_COMMIT
  ############################################
  - ls -al

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    name: $TRAVIS_TAG
    #body: "$RELEASE_DESCRIPTION" # https://github.com/travis-ci/dpl/issues/155
    overwrite: true
    prerelease: true
    skip_cleanup: true
    file:
      - "./RELEASES/all_files.zip"
      - "./RELEASES/sd_image.iso.zip"
    on:
      tags: false
      branch: 
        - master
        - travisci
  - provider: releases
    api_key: $GITHUB_TOKEN
    name: $TRAVIS_TAG
    #body: "$RELEASE_DESCRIPTION" # https://github.com/travis-ci/dpl/issues/155
    overwrite: true
    prerelease: false
    skip_cleanup: true
    file_glob: true
    file: "./RELEASES*/*"
    on:
      tags: true
  - provider: pages
    github-token: $GITHUB_TOKEN
    skip-cleanup: true
    keep-history: false
    #target-branch: $TRAVIS_BRANCH
    on:
      branch: 
        - master

after_deploy:
  - ls -al

after_script:
  - ls -al
